name: RFMX
version: '${project.version}'
main: snw.rfmx.RFMX
api-version: 1.16

depend:
  - RunForMoney
loadbefore:
  - RunForMoney

commands:
  clearcoin:
    description: "使所有仍存活的玩家 (排除已被捕或弃权的玩家) 所拥有的 B币 数量归零。谨慎操作。"
    usage: "/clearcoin"
    permission: op
    permission-message: "§c你没有权限执行此操作。"
  hunternomove:
    description: "使全体猎人不能移动，可以指定时长。time 为目标时长 (秒为单位，当提供的值不是正数时取消禁止移动)。"
    usage: "/hunternomove <time: int>"
    permission: op
    permission-message: "§c你没有权限执行此操作。"
  setcoinpersecond:
    description: "设置每秒增加的B币数量。参数不能为 0 。"
    usage: "/setcoinpersecond <coin: int>"
    permission: op
    permission-message: "§c你没有权限执行此操作。"